# Generated by Django 5.1.4 on 2024-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
